[package]
name = "vitters-algorithm"
version = "0.1.0"
authors = ["Mads Marquart <madsmtm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
